### ISSUE TITLE
AttributeError: module 'vnpy_sqlite' has no attribute 'Database'

### ISSUE THREAD

**Issue by mbshqqb** [vnpy/vnpy_sqlite#7]
没有配置要使用的数据服务，请修改全局配置中的datafeed相关内容
Traceback (most recent call last):
  File "E:\Workspace\Python\vnpy\examples\veighna_trader\run.py", line 101, in <module>
    main()
  File "E:\Workspace\Python\vnpy\examples\veighna_trader\run.py", line 85, in main
    main_engine.add_app(ChartWizardApp)
  File "E:\Workspace\Python\vnpy\vnpy\trader\engine.py", line 102, in add_app
    engine: BaseEngine = self.add_engine(app.engine_class)
  File "E:\Workspace\Python\vnpy\vnpy\trader\engine.py", line 73, in add_engine
    engine: BaseEngine = engine_class(self, self.event_engine)
  File "E:\Workspace\Python\vnpy\vnpy_chartwizard\engine.py", line 29, in __init__
    self.database: BaseDatabase = get_database()
  File "E:\Workspace\Python\vnpy\vnpy\trader\database.py", line 158, in get_database
    database = module.Database()
AttributeError: module 'vnpy_sqlite' has no attribute 'Database'

**Comment by vnpy** [comment]
运行下述命令升级到新版本试试：

`pip install vnpy_sqlite --upgrade`
